version: '3.4'

services:
  web:
    build: ./pet
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./pet/:/usr/src/app/
    ports:
    - 8000:8000
    env_file:
    - ./pet/envs/.env
    depends_on:
    - postgres
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: pet_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./postgresql:/var/lib/postgresql/data