# Generated by Django 4.2.2 on 2023-09-06 11:20

import cloudinary.models
from django.db import migrations
import pet.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[pet.photos.validators.validate_file_less_than_5mb], verbose_name='image'),
        ),
    ]
