# Generated by Django 4.2.2 on 2023-09-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_photo_alter_photo_photo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo2',
            new_name='photo',
        ),
    ]
